Removed unnecessary absolute paths

diff --git a/.github/workflows/converge_nodes.yml b/.github/workflows/converge_nodes.yml
--- a/.github/workflows/converge_nodes.yml
+++ b/.github/workflows/converge_nodes.yml
@@ -32,10 +32,10 @@ jobs:
     steps:
       - name: Create/push Policyfile.lock to ChefServer
         run: |
-          chef update policyfiles/db-server.rb -c /home/r-goto/.chef/config.rb
-          chef update policyfiles/web-server.rb -c /home/r-goto/.chef/config.rb
-          chef push production policyfiles/db-server.rb -c /home/r-goto/.chef/config.rb
-          chef push production policyfiles/web-server.rb -c /home/r-goto/.chef/config.rb
+          chef update policyfiles/db-server.rb -c .chef/config.rb
+          chef update policyfiles/web-server.rb -c .chef/config.rb
+          chef push production policyfiles/db-server.rb -c .chef/config.rb
+          chef push production policyfiles/web-server.rb -c .chef/config.rb
   
   Converge-Nodes:
     environment:
@@ -46,7 +46,7 @@ jobs:
     steps:
       - name: Converge all production nodes
         run: 
-          knife ssh 'policy_group:production' 'sudo chef-client' -c /home/r-goto/.chef/config.rb
+          knife ssh 'policy_group:production' 'sudo chef-client' -c .chef/config.rb
   Test:
     runs-on: self-hosted
     needs: Converge-Nodes
@@ -54,5 +54,5 @@ jobs:
       - name: Run Inspec
         continue-on-error: true
         run: |
-          for i in `knife search 'policy_group:production AND policy_name:web-server' -i -c /home/r-goto/.chef/config.rb | sort`; do inspec exec $GITHUB_WORKSPACE/test/setup_nginx_test.rb --target ssh://r-goto@$i -i ~/.ssh/nodes_shared || echo 'Inspec failure!'; done
-          for i in `knife search 'policy_group:production AND policy_name:db-server' -i -c /home/r-goto/.chef/config.rb | sort`; do inspec exec $GITHUB_WORKSPACE/test/setup_postgresql_test.rb --target ssh://r-goto@$i -i ~/.ssh/nodes_shared || echo 'Inspec failure!'; done
+          for i in `knife search 'policy_group:production AND policy_name:web-server' -i -c .chef/config.rb | sort`; do inspec exec $GITHUB_WORKSPACE/test/setup_nginx_test.rb --target ssh://r-goto@$i -i ~/.ssh/nodes_shared || echo 'Inspec failure!'; done
+          for i in `knife search 'policy_group:production AND policy_name:db-server' -i -c .chef/config.rb | sort`; do inspec exec $GITHUB_WORKSPACE/test/setup_postgresql_test.rb --target ssh://r-goto@$i -i ~/.ssh/nodes_shared || echo 'Inspec failure!'; done
